#pragma once

#include "./core/BBox3.h"
#include "./core/BBox2.h"
#include "./core/Quaternion.h"
#include "./core/Config.h"
#include "./core/ScriptFile.h"
#include "./core/Vertex.h"
#include "./core/ViewFrustum.h"
#include "./core/TDynamicTab.h"
#include "./core/TSingleton.h"
#include "./core/FileSystemFactory.h"
#include "./core/Camera.h"
#include "./core/Stat.h"
#include "./core/TDataBase.h"
#include "./core/TList.h"
#include "./core/TVector.h"
#include "./core/TSet.h"
#include "./core/Rect.h"
#include "./core/MatrixTab.h"
#include "./core/MatrixHierarchy.h"
#include "./core/AnimTracks.h"
#include "./core/TAllocated.h"
#include "./core/CharUtil.h"
#include "./core/Random.h"

void initShadowCore();
